// SPDX-License-Identifier: AGPL-3.0-or-later
//
// schema.ts — the authoritative ajv validator for model output (plan §6.4, §7).
//
// Goose performs its own best-effort schema check via `response.json_schema`,
// but THIS validator is the authority (defense in depth): nothing reaches the
// anchor/post stages without passing here. It compiles the generated LOOSE
// variant (schema/review-output.loose.schema.json), which is the exact shape
// the model is asked to satisfy. The loose file is generated by build-schemas.ts
// from the canonical base, and CI git-diff-gates it so the recipe, validator,
// and direct path can never drift.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv, { type ValidateFunction } from "ajv";
import type { ReviewOutput } from "./types";

const here = dirname(fileURLToPath(import.meta.url));
// scripts/pr-review/lib -> repo root is three directories up.
const LOOSE_SCHEMA_PATH = join(here, "..", "..", "..", "schema", "review-output.loose.schema.json");

export type ValidationResult = { ok: true; value: ReviewOutput } | { ok: false; errors: string[] };

let cachedValidate: ValidateFunction | null = null;

function getValidator(): ValidateFunction {
  if (cachedValidate) return cachedValidate;
  const schema = JSON.parse(readFileSync(LOOSE_SCHEMA_PATH, "utf8")) as object;
  // allErrors so a single validation pass reports every problem for the audit log.
  const ajv = new Ajv({ allErrors: true, strict: false });
  cachedValidate = ajv.compile(schema);
  return cachedValidate;
}

/**
 * Validate an arbitrary parsed JSON value against the loose review schema.
 * On success the value is returned narrowed to ReviewOutput; on failure a list
 * of human-readable ajv error strings is returned for the audit trail.
 */
export function validateReviewOutput(value: unknown): ValidationResult {
  const validate = getValidator();
  if (validate(value)) {
    return { ok: true, value: value as ReviewOutput };
  }
  const errors = (validate.errors ?? []).map(
    (e) => `${e.instancePath || "(root)"} ${e.message ?? "invalid"}`,
  );
  return { ok: false, errors: errors.length > 0 ? errors : ["unknown validation error"] };
}
