// SPDX-License-Identifier: AGPL-3.0-or-later
import { defineConfig } from "wxt";

// The manifest is GENERATED by WXT — never hand-author manifest.json.
// All permission/identity facts live here so the privacy invariant
// (host_permissions = docs.google.com only; permissions = storage only)
// is enforced at config time.
//
// Build determinism (Phase 7): the UnoCSS theme-variable ordering that would
// otherwise make back-to-back builds non-reproducible is normalized in
// uno.config.ts via a `post` SourceCodeTransformer — it must run before Vite
// hashes the CSS asset, which a Vite plugin here cannot do. See uno.config.ts.
export default defineConfig({
  modules: ["@wxt-dev/module-solid", "@wxt-dev/unocss"],
  // Silence ONE known-benign UnoCSS build warning, nothing else.
  //
  // @unocss/vite global build mode resolves the `uno` layer the first time
  // `virtual:uno.css` is imported and caches it (vfsLayers); every LATER importer
  // hits the `vfsLayers.has(layer)` branch and emits
  //   "[unocss] "virtual:uno.css" is being imported multiple times … using the
  //    first occurrence"
  // (@unocss/vite/dist/index.mjs:520-522). DocRewind has four legitimate
  // importers — the options, popup and replay page mounts plus the docs content
  // script — and each MUST import the stylesheet so the shared CSS chunk is linked
  // into its own output. The dedup-to-one-chunk this warns about is exactly the
  // behaviour we rely on (see the `safelist` note in uno.config.ts), so the warning
  // is pure noise. Drop precisely this message via Rollup's onwarn and forward
  // everything else untouched; this only affects production builds.
  vite: () => ({
    // ES output for bundled Web Workers so the per-kind dynamic imports in
    // entrypoints/replay/parse.worker.ts actually code-split (the default iife
    // worker format cannot code-split and would inline all three editor cores
    // back into one bundle). The worker is already `type: "module"`, so both
    // engines' support floors are unchanged by this.
    worker: { format: "es" as const },
    build: {
      rollupOptions: {
        onwarn(warning, defaultHandler) {
          const msg = typeof warning === "string" ? warning : warning.message;
          if (msg?.includes("virtual:uno.css") && msg.includes("imported multiple times")) {
            return;
          }
          defaultHandler(warning);
        },
      },
    },
  }),
  // Build BOTH browsers as MV3 (Firefox would otherwise default to MV2).
  manifestVersion: 3,
  manifest: ({ browser }) => ({
    name: "DocRewind",
    description: "Local-first Google Docs revision-replay browser extension.",
    permissions: ["storage"],
    host_permissions: ["*://docs.google.com/*"],
    ...(browser === "firefox"
      ? { browser_specific_settings: { gecko: { id: "docrewind@edbpede.github.io" } } }
      : {}),
  }),
  // No DOM in the background — exclude it from UnoCSS processing.
  unocss: { excludeEntrypoints: ["background"] },
});
