// SPDX-License-Identifier: AGPL-3.0-or-later
//
// CONTENT-FREE live-capture fixture for the Sheets (Ritz) decoder (plan Phase 5;
// ground truth .omc/plans/sheets-ritz-format-findings.md, capture 2026-06-30).
//
// Generated by sanitizing a real 26-revision `revisions/load` read of a throwaway
// Google Sheet (modelVersion 99). Every OPCODE and structural SHAPE (ranges,
// anchors, gids, the merge/opaque/chart-datasource/cond-format/reorder families)
// is preserved verbatim so the decode + reconstruction pipeline behaves exactly as
// on the wire; every human string (cell text, sheet names, object labels, locale)
// is neutralized to "x" and the identity tuple fields (time[1], userId[2],
// sessionId[4]) are redacted to synthetic placeholders. Numeric-string gids/object
// ids are kept because they are content-free structural keys, not user data.
//
// This is the Sheets counterpart to lib/core/fixtures/captured.ts (the Docs live
// fixture). `envelope` is the framed-and-parsed `{ chunkedSnapshot, changelog }`
// payload exactly as the worker hands it to the Sheets pipeline.

/** The sanitized 26-revision Sheets capture envelope (parsed, content-free). */
export const SHEETS_CAPTURED_HISTORY: { readonly envelope: unknown } = {
  envelope: {
    chunkedSnapshot: [
      [
        [
          25104121,
          [
            null,
            0,
            1,
            [],
            null,
            null,
            1,
            [],
            1,
            [],
            1,
            [],
            1,
            [],
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
          ],
        ],
        [
          25104121,
          [
            null,
            2,
            1,
            [],
            null,
            null,
            1,
            [],
            1,
            [],
            1,
            [],
            1,
            [],
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
          ],
        ],
        [
          25104121,
          [
            null,
            1,
            1,
            [],
            null,
            null,
            1,
            [],
            1,
            [],
            1,
            [],
            1,
            [],
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
          ],
        ],
        [
          28950036,
          {
            "1": {
              "1": [
                [null, 2, 0, "x"],
                {
                  "1": 10,
                  "2": 0,
                  "11": 21,
                },
                {
                  "1": 11,
                  "2": 0,
                  "12": 120,
                },
              ],
            },
          },
        ],
      ],
    ],
    changelog: [
      [
        [
          4444216,
          [
            [
              28950036,
              {
                "1": [
                  null,
                  [
                    [null, 2, 0, "x"],
                    {
                      "1": 11,
                      "2": 0,
                      "12": 100,
                    },
                    {
                      "1": 9,
                      "2": 0,
                      "10": {
                        "2": 256,
                        "11": 0,
                      },
                    },
                  ],
                  1,
                ],
              },
            ],
            [
              21350203,
              [
                null,
                0,
                0,
                "0",
                {
                  "1": [
                    [null, 0, 0, "x"],
                    {
                      "1": 2,
                      "2": 0,
                      "5": 0,
                    },
                    {
                      "1": 3,
                      "2": 0,
                      "6": 0,
                    },
                    {
                      "1": 4,
                      "2": 0,
                      "7": 0,
                    },
                    {
                      "1": 5,
                      "2": 0,
                      "8": 0,
                    },
                    {
                      "1": 6,
                      "2": 0,
                      "9": 0,
                    },
                  ],
                },
                1000,
                26,
              ],
            ],
            [
              28950036,
              {
                "1": {
                  "1": [
                    {
                      "1": 4,
                      "2": 0,
                      "5": 1,
                    },
                  ],
                },
              },
            ],
            [
              149980211,
              [
                null,
                "0",
                {
                  "1": [
                    [null, 2, 1, null, 1782821124356],
                    {
                      "1": 3,
                      "2": 1,
                      "5": 1782821124356,
                    },
                  ],
                },
              ],
            ],
            [
              25104121,
              {
                "1": 0,
                "2": 2,
                "8": 2,
                "10": 2,
                "12": 2,
                "16": 2,
                "23": 2,
                "25": 2,
              },
            ],
            [
              25104121,
              {
                "1": 2,
                "2": 2,
                "8": 2,
                "10": 2,
                "12": 2,
                "16": 2,
                "23": 2,
                "25": 2,
              },
            ],
            [
              25104121,
              {
                "1": 1,
                "2": 2,
                "8": 2,
                "10": 2,
                "12": 2,
                "16": 2,
                "23": 2,
                "25": 2,
              },
            ],
          ],
        ],
        1000,
        "user-redacted",
        1,
        "sess-redacted",
        null,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              25104121,
              [
                null,
                0,
                3,
                {
                  "1": [
                    {
                      "1": "0",
                    },
                  ],
                },
              ],
            ],
            [
              28950036,
              {
                "1": {
                  "1": [
                    [null, 2, 0, "x"],
                    [null, 3, 0, null, "x"],
                  ],
                },
              },
            ],
          ],
        ],
        1001,
        "user-redacted",
        2,
        "sess-redacted",
        0,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 0, 1],
            [
              null,
              132274236,
              3,
              {
                "1": 3,
                "3": 12345,
              },
              null,
              null,
              0,
            ],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1002,
        "user-redacted",
        3,
        "sess-redacted",
        0,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 3, 4, 0, 1],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1003,
        "user-redacted",
        4,
        "sess-redacted",
        1,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 1, 2],
            [
              null,
              132274236,
              3,
              {
                "1": 3,
                "3": 9999,
              },
              null,
              null,
              0,
            ],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1004,
        "user-redacted",
        5,
        "sess-redacted",
        2,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 1, 2],
            {
              "1": 32,
              "2": 2,
              "6": 0,
            },
            {
              "2": [
                {
                  "2": 1,
                  "3": [null, 4, "x"],
                },
              ],
            },
          ],
        ],
        1005,
        "user-redacted",
        6,
        "sess-redacted",
        3,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 3, 4],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1006,
        "user-redacted",
        7,
        "sess-redacted",
        4,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 0, 1, 5, 6],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1007,
        "user-redacted",
        8,
        "sess-redacted",
        5,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              21299578,
              [
                null,
                [null, "0", 0, 1, 5, 6],
                {
                  "1": 2,
                },
                [],
              ],
            ],
            [
              21299578,
              [
                null,
                [null, "0", 0, 1, 5, 6],
                {
                  "1": 132274237,
                },
                [],
              ],
            ],
          ],
        ],
        1008,
        "user-redacted",
        9,
        "sess-redacted",
        6,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 0, 1, 6, 7],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1009,
        "user-redacted",
        10,
        "sess-redacted",
        7,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 6, 7],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1010,
        "user-redacted",
        11,
        "sess-redacted",
        8,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 1, 2, 6, 7],
            {
              "2": 2,
              "6": 0,
            },
            {
              "2": [
                {
                  "2": 16384,
                  "17": 1,
                },
              ],
            },
          ],
        ],
        1011,
        "user-redacted",
        12,
        "sess-redacted",
        9,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 2, 3, 6, 7],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1012,
        "user-redacted",
        13,
        "sess-redacted",
        10,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              21299578,
              [
                null,
                [null, "0", 2, 3, 6, 7],
                {
                  "1": 2,
                },
                [],
              ],
            ],
            [
              21299578,
              [
                null,
                [null, "0", 2, 3, 6, 7],
                {
                  "1": 132274237,
                },
                [],
              ],
            ],
          ],
        ],
        1013,
        "user-redacted",
        14,
        "sess-redacted",
        11,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              21350203,
              [
                null,
                1,
                0,
                "849076485",
                {
                  "1": [
                    [null, 0, 0, "x"],
                    {
                      "1": 2,
                      "2": 0,
                      "5": 0,
                    },
                    {
                      "1": 3,
                      "2": 0,
                      "6": 0,
                    },
                    {
                      "1": 4,
                      "2": 0,
                      "7": 0,
                    },
                    {
                      "1": 5,
                      "2": 0,
                      "8": 0,
                    },
                    {
                      "1": 6,
                      "2": 0,
                      "9": 0,
                    },
                  ],
                },
                1000,
                26,
              ],
            ],
            [
              28950036,
              {
                "1": {
                  "1": [
                    {
                      "1": 4,
                      "2": 0,
                      "5": 2,
                    },
                  ],
                },
              },
            ],
          ],
        ],
        1014,
        "user-redacted",
        15,
        "sess-redacted",
        12,
        null,
        null,
        false,
      ],
      [
        [
          26812461,
          [
            null,
            "0",
            {
              "1": [[null, 0, 0, "x"]],
            },
          ],
        ],
        1015,
        "user-redacted",
        16,
        "sess-redacted",
        13,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [24502104, [null, "0", 0, 1, 0, 0]],
            [
              25813757,
              [
                null,
                [null, "0", 0, 1, 6, 7],
                {
                  "2": [
                    {
                      "2": 513,
                      "3": {
                        "1": 0,
                      },
                      "12": 0,
                    },
                  ],
                  "6": [
                    {
                      "1": 32,
                      "2": 2,
                      "6": 0,
                    },
                  ],
                  "8": [0],
                  "9": [6],
                },
              ],
            ],
          ],
        ],
        1016,
        "user-redacted",
        17,
        "sess-redacted",
        14,
        null,
        null,
        false,
      ],
      [
        [24502104, [null, "0", 7, 2, 1, 0]],
        1017,
        "user-redacted",
        18,
        "sess-redacted",
        15,
        null,
        null,
        false,
      ],
      [
        [25037233, [null, "0", 4, 1, 0]],
        1018,
        "user-redacted",
        19,
        "sess-redacted",
        16,
        null,
        null,
        false,
      ],
      [
        [25037233, [null, "0", 1, 2, 1]],
        1019,
        "user-redacted",
        20,
        "sess-redacted",
        17,
        null,
        null,
        false,
      ],
      [
        [
          21299578,
          [
            null,
            [null, "0", 14, 15, 0, 1],
            [null, 132274236, 3, [null, 2, "x"], null, null, 0],
            {
              "2": [
                {
                  "2": 513,
                  "3": {
                    "1": 0,
                  },
                  "12": 0,
                },
              ],
            },
          ],
        ],
        1020,
        "user-redacted",
        21,
        "sess-redacted",
        0,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              21299578,
              [
                null,
                [null, "0", 0, 1, 1, 2],
                {
                  "1": 1206353791,
                },
                [],
              ],
            ],
            [
              27911206,
              {
                "1": [null, "0", 0, 1, 0, 2],
              },
            ],
          ],
        ],
        1021,
        "user-redacted",
        22,
        "sess-redacted",
        1,
        null,
        null,
        false,
      ],
      [
        [
          4444216,
          [
            [
              34070425,
              [
                null,
                "1430258216",
                [null, "0", 2, 3, 0, 2],
                3,
                {
                  "2": 1,
                  "3": "974979131",
                },
              ],
            ],
            [
              27809640,
              {
                "1": [
                  null,
                  "974979131",
                  {
                    "1": 3,
                    "3": [
                      null,
                      null,
                      ["1430258216"],
                      0,
                      -1,
                      0,
                      null,
                      null,
                      0,
                      null,
                      {
                        "3": 5,
                        "4": [],
                      },
                    ],
                  },
                  [null, 0, "0", [null, 1, 0], 57, 33, 600, 371, 1],
                  null,
                  "x",
                ],
              },
            ],
          ],
        ],
        1022,
        "user-redacted",
        23,
        "sess-redacted",
        2,
        null,
        null,
        false,
      ],
      [
        [
          45416218,
          [
            null,
            "0",
            0,
            [
              null,
              [[null, "0", 2, 5, 0, 1]],
              [
                null,
                [
                  null,
                  {
                    "1": 26,
                  },
                  {
                    "1": {
                      "1": [
                        {
                          "1": 4,
                          "6": 0,
                        },
                        [null, 2, null, "x", 1],
                        [null, 2, null, "x", 1],
                        [null, 1, "x"],
                      ],
                    },
                    "3": "x",
                  },
                  [[null, [null, 0, 1, 0, 1, 1118464], 0]],
                ],
                [null, 33554432, 2, null, [null, 2, 12050893]],
              ],
            ],
          ],
        ],
        1023,
        "user-redacted",
        24,
        "sess-redacted",
        3,
        null,
        null,
        false,
      ],
      [[31997291, [null, 0, 2]], 1024, "user-redacted", 25, "sess-redacted", 0, null, null, false],
      [
        [
          27809640,
          {
            "1": [
              null,
              "501988802",
              [null, 2, [null, 2, "x", null, 2048, 2048]],
              [null, 0, "0", [null, 14, 5], 16, 16, 402, 402, 2],
              null,
              "x",
            ],
          },
        ],
        1025,
        "user-redacted",
        26,
        "sess-redacted",
        1,
        null,
        null,
        false,
      ],
    ],
  },
};
